"""Add message tracking columns

Revision ID: 1d7fc26b461d
Revises: 3dd773ad4c5c
Create Date: 2025-01-20 09:56:05.972994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7fc26b461d'
down_revision: Union[str, None] = '3dd773ad4c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_dates', sa.Column('is_announcement_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('game_dates', sa.Column('is_start_message_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_dates', 'is_start_message_sent')
    op.drop_column('game_dates', 'is_announcement_sent')
    # ### end Alembic commands ###
