"""Init

Revision ID: 3dd773ad4c5c
Revises: 
Create Date: 2025-01-17 09:58:01.673531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd773ad4c5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_dates',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_dates')
    # ### end Alembic commands ###
