"""add subscriber notification flags and bot_blocked

Revision ID: 9e5a62ea4a2b
Revises: 8923bd051668
Create Date: 2025-11-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5a62ea4a2b'
down_revision: Union[str, None] = '8923bd051668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавление флага bot_blocked в таблицу users
    op.add_column('users', sa.Column('bot_blocked', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # Добавление флагов уведомлений в таблицу user_game_subscription
    op.add_column('user_game_subscription', sa.Column('is_equator_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_game_subscription', sa.Column('is_2days_before_end_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user_game_subscription', sa.Column('is_game_started_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаление флагов уведомлений из таблицы user_game_subscription
    op.drop_column('user_game_subscription', 'is_game_started_notified')
    op.drop_column('user_game_subscription', 'is_2days_before_end_notified')
    op.drop_column('user_game_subscription', 'is_equator_notified')

    # Удаление флага bot_blocked из таблицы users
    op.drop_column('users', 'bot_blocked')
    # ### end Alembic commands ###
