"""image field added

Revision ID: 9fd132be7a02
Revises: 8923bd051668
Create Date: 2025-02-14 13:27:56.972067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd132be7a02'
down_revision: Union[str, None] = '8923bd051668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_dates', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_dates', 'image')
    # ### end Alembic commands ###
